In [1]:
from dog_datasets.Dog import DogBreed

ModuleNotFoundError: No module named 'torchvision'

In [2]:
a=DogBreed(label_file="/home/huxiaomeng/dl/dl_3/datasets/dog-breed-identification/labels.csv",img_dir="/home/huxiaomeng/dl/dl_3/datasets/dog-breed-identification/train")

creating img-label mapping...: 10223it [00:00, 219079.05it/s]


In [6]:
a=[]
with open("/home/huxiaomeng/dl/dl_3/datasets/class_name.txt",'r') as f:
    for item in f:
        a.append(item.strip('\n'))

In [8]:
a

['affenpinscher',
 'afghan_hound',
 'african_hunting_dog',
 'airedale',
 'american_staffordshire_terrier',
 'appenzeller',
 'australian_terrier',
 'basenji',
 'basset',
 'beagle',
 'bedlington_terrier',
 'bernese_mountain_dog',
 'black-and-tan_coonhound',
 'blenheim_spaniel',
 'bloodhound',
 'bluetick',
 'border_collie',
 'border_terrier',
 'borzoi',
 'boston_bull',
 'bouvier_des_flandres',
 'boxer',
 'brabancon_griffon',
 'briard',
 'brittany_spaniel',
 'bull_mastiff',
 'cairn',
 'cardigan',
 'chesapeake_bay_retriever',
 'chihuahua',
 'chow',
 'clumber',
 'cocker_spaniel',
 'collie',
 'curly-coated_retriever',
 'dandie_dinmont',
 'dhole',
 'dingo',
 'doberman',
 'english_foxhound',
 'english_setter',
 'english_springer',
 'entlebucher',
 'eskimo_dog',
 'flat-coated_retriever',
 'french_bulldog',
 'german_shepherd',
 'german_short-haired_pointer',
 'giant_schnauzer',
 'golden_retriever',
 'gordon_setter',
 'great_dane',
 'great_pyrenees',
 'greater_swiss_mountain_dog',
 'groenendael',


In [3]:
a.classes

['boston_bull',
 'dingo',
 'pekinese',
 'bluetick',
 'golden_retriever',
 'bedlington_terrier',
 'borzoi',
 'basenji',
 'scottish_deerhound',
 'shetland_sheepdog',
 'walker_hound',
 'maltese_dog',
 'norfolk_terrier',
 'african_hunting_dog',
 'wire-haired_fox_terrier',
 'redbone',
 'lakeland_terrier',
 'boxer',
 'doberman',
 'otterhound',
 'standard_schnauzer',
 'irish_water_spaniel',
 'black-and-tan_coonhound',
 'cairn',
 'affenpinscher',
 'labrador_retriever',
 'ibizan_hound',
 'english_setter',
 'weimaraner',
 'giant_schnauzer',
 'groenendael',
 'dhole',
 'toy_poodle',
 'border_terrier',
 'tibetan_terrier',
 'norwegian_elkhound',
 'shih-tzu',
 'irish_terrier',
 'kuvasz',
 'german_shepherd',
 'greater_swiss_mountain_dog',
 'basset',
 'australian_terrier',
 'schipperke',
 'rhodesian_ridgeback',
 'irish_setter',
 'appenzeller',
 'bloodhound',
 'samoyed',
 'miniature_schnauzer',
 'brittany_spaniel',
 'kelpie',
 'papillon',
 'border_collie',
 'entlebucher',
 'collie',
 'malamute',
 'welsh

In [2]:
import torch.nn as nn
nn.AdaptiveAvgPool1d()

In [7]:
m = nn.AdaptiveAvgPool1d(5)
input = torch.randn(7,6,8)
m(input).shape

torch.Size([7, 6, 5])

In [8]:
nn.ReLU()

ReLU()

In [27]:
import torch
a=torch.tensor([[ 0.1, -0.6, -0.8],
        [-0.8,  1.0861, -0.3781],
        [-1.3996,  1.6145, -0.8311],
        [-0.5138,  1.8, -1.0164],
        [-0.4463,  0.6781,  1.6281]])

In [25]:
a=torch.tensor([10,2,36,4])

In [29]:
a

tensor([[ 0.1000, -0.6000, -0.8000],
        [-0.8000,  1.0861, -0.3781],
        [-1.3996,  1.6145, -0.8311],
        [-0.5138,  1.8000, -1.0164],
        [-0.4463,  0.6781,  1.6281]])

In [28]:
a.tolist()

[[0.10000000149011612, -0.6000000238418579, -0.800000011920929],
 [-0.800000011920929, 1.0860999822616577, -0.3781000077724457],
 [-1.3996000289916992, 1.6145000457763672, -0.8310999870300293],
 [-0.5138000249862671, 1.7999999523162842, -1.0163999795913696],
 [-0.4462999999523163, 0.6780999898910522, 1.628100037574768]]

In [24]:
nn.BatchNorm2d(a)

TypeError: empty() received an invalid combination of arguments - got (Tensor, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [16]:
b=a.sum(1)

In [18]:
b

tensor([-0.2385,  0.1308, -0.6162,  0.1660,  1.8598])

In [ ]:
nn.soft

In [11]:
torchvision.models.vgg11(True)

Downloading: "https://download.pytorch.org/models/vgg11-8a719046.pth" to /home/huxiaomeng/.cache/torch/hub/checkpoints/vgg11-8a719046.pth


KeyboardInterrupt: 

In [3]:
import os
st=torch.load("/home/huxiaomeng/dl/dl_3/pretrained_models/resnet18/resnet18-f37072fd.pth")

In [6]:
a.load_state_dict(st)

<All keys matched successfully>

In [1]:
from src.models.resnet18 import ResNet,Block

In [5]:
a=ResNet(18,Block,3,1000)

In [24]:
torch.stack([torch.tensor(item) for item in a])

tensor([5, 6, 7])

In [12]:
a=torch.ones(4,5,6)
b=torch.zeros(4,5,6)

In [16]:
torch.stack([a,b]).shape

torch.Size([2, 4, 5, 6])

In [18]:
b.state_dict()

OrderedDict([('features.0.weight',
              tensor([[[[ 3.3738e-02, -4.3409e-03,  5.0043e-02],
                        [ 7.7380e-02, -6.1545e-02,  2.6765e-02],
                        [-5.8794e-02,  6.4017e-02, -5.0981e-02]],
              
                       [[ 2.6092e-02, -1.6189e-01, -2.0175e-03],
                        [-1.7562e-02,  6.8067e-02,  1.4713e-02],
                        [-5.6661e-02,  8.7273e-02,  6.9509e-02]],
              
                       [[-7.0752e-02,  1.8833e-02, -9.5864e-03],
                        [-3.0395e-02, -5.6186e-02,  4.6856e-02],
                        [ 7.7979e-02, -4.9558e-02,  5.8008e-02]]],
              
              
                      [[[-6.2505e-02, -4.2713e-02,  2.1316e-03],
                        [-1.0699e-02, -4.9096e-02, -1.8764e-02],
                        [ 1.2471e-02,  3.5172e-03, -4.7789e-02]],
              
                       [[-2.3670e-02,  4.9673e-02, -4.8609e-02],
                        [-2.6751e-02,  3

In [3]:
import torch.nn as nn


In [6]:
a=torch.rand(3,5)

In [14]:
a

tensor([[0.5693, 0.1680, 0.9870, 0.5599, 0.6183],
        [0.1156, 0.7553, 0.0136, 0.5715, 0.8537],
        [0.5054, 0.1984, 0.2609, 0.0879, 0.3581]])

In [12]:
f=nn.Softmax(dim=1)

In [16]:
b=f(a)

In [12]:
a=[1,2,3]
import random

In [19]:
len(os.listdir("/home/huxiaomeng/dl/dl_3/datasets/dog-breed-identification/train"))

9044

In [21]:
mean([1,2,3])

NameError: name 'mean' is not defined

In [13]:
a

[1, 2, 3]

In [30]:
b.to("cuda:0")

tensor([[0.1913, 0.1280, 0.2904, 0.1895, 0.2009],
        [0.1339, 0.2539, 0.1209, 0.2112, 0.2801],
        [0.2475, 0.1821, 0.1938, 0.1630, 0.2136]], device='cuda:0')

In [32]:
b.tolist()

[[0.19125309586524963,
  0.12802864611148834,
  0.29040011763572693,
  0.18945641815662384,
  0.20086169242858887],
 [0.13389399647712708,
  0.25385531783103943,
  0.12090732902288437,
  0.21122846007347107,
  0.28011491894721985],
 [0.2474880963563919,
  0.18207144737243652,
  0.1938154399394989,
  0.1630232036113739,
  0.21360182762145996]]

In [25]:
c=b[0].tolist()

In [27]:
','.join([str(item) for item in c])

'0.19125309586524963,0.12802864611148834,0.29040011763572693,0.18945641815662384,0.20086169242858887'

In [28]:
"ideoihf.jpg".strip(".jpg")

'ideoihf'

In [7]:
b.state_dict().keys()

odict_keys(['features.0.weight', 'features.0.bias', 'features.3.weight', 'features.3.bias', 'features.6.weight', 'features.6.bias', 'features.8.weight', 'features.8.bias', 'features.11.weight', 'features.11.bias', 'features.13.weight', 'features.13.bias', 'features.16.weight', 'features.16.bias', 'features.18.weight', 'features.18.bias', 'classifier.0.weight', 'classifier.0.bias', 'classifier.3.weight', 'classifier.3.bias', 'classifier.6.weight', 'classifier.6.bias'])

In [8]:
torch.save(b.state_dict(),"vgg11_pm_weight.bin")

In [4]:
import torch.nn  as nn

In [11]:
a=nn.ReLU(inplace=True)

In [15]:
nn.AdaptiveAvgPool2d(output_size=(7, 7))

AdaptiveAvgPool2d(output_size=(7, 7))

In [3]:
from src.models.vgg11 import VGG11
a=VGG11(3,102)

In [22]:

map_weight=a.map.state_dict()

In [23]:
net=torch.load("vgg11_pm_weight.bin")
map_weight.update(net)

In [24]:
a.load_state_dict(map_weight,strict=False)

_IncompatibleKeys(missing_keys=['map.2.weight', 'map.2.bias'], unexpected_keys=['2.weight', '2.bias'])

In [6]:
torch.save(a.map.state_dict(),"vgg11_map_weight.bin")

In [28]:
a=['1','2']
'id,'+','.join(a)+'\n'

'id,1,2\n'

In [ ]:
import os
os.list()